[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.33"
ignored_error_codes = [2424,5574]
evm_version = "osaka"



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
